# Generated by Django 4.2 on 2023-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackofenHerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bosch', 'Bosch'), ('Siemens', 'Siemens'), ('other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EinbauBackofen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bosch', 'Bosch'), ('Siemens', 'Siemens'), ('other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kuehlschrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bosch', 'Bosch'), ('Siemens', 'Siemens'), ('other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spuelmaschine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bosch', 'Bosch'), ('Siemens', 'Siemens'), ('other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verkaufen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Waschmaschine', 'Waschmaschine'), ('Spuelmaschine', 'Spuelmaschine'), ('EinbauBackofen', 'EinbauBackofen'), ('BackofenHerd', 'BackofenHerd'), ('Kuehlschrank', 'Kuehlschrank')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Waschmaschine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bosch', 'Bosch'), ('Siemens', 'Siemens'), ('other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
    ]
