# Generated by Django 4.2 on 2023-04-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_backofen_delete_einbaubackofen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backofen',
            name='anzahl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='backofenherd',
            name='anzahl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kuehlschrank',
            name='anzahl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='spuelmaschine',
            name='anzahl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='waschmaschine',
            name='anzahl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='backofenherd',
            name='iduktion',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Nein', 'Nein'), ('Nicht sicher', 'Nicht sicher')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
